### ISSUE TITLE
Panic: Value has already been added to the cache

### ISSUE THREAD

**Issue by mariamalikorg** [cockroachdb/pebble#2527] opened 2023-05-15 18:11 UTC
Hello,
I am using cockroach-pebble to evaluate the performance on my system but the CRDB server node crashes with the panic-triggered msg.

"Wraps: (2) panic: pebble: Value has already been added to the cache: refs=0
* Error types: (1) *withstack.withStack (2) *errutil.leafError"

Test setup:
![image](https://github.com/cockroachdb/pebble/assets/87718561/23bafe16-d3c3-4229-88fb-9ddfb5d05a6e)

cockroach start-single-node --insecure --advertise-addr=x.x.x.x --store="/root/cockroach-data,pebble=[Level \"6\"] compression=ZSTD" --background

A client running go-ycsb to generate data.

I have built the CRDB binary after updating the zstd version to 1.5.5 from 1.5.2. My initial suspension is that the zstd version upgrade is causing this issue. The help I need to figure out how to address this panic-triggered issue w/ the latest zstd version.

Thank you

**Comment by nicktrav** [comment] 2023-05-15 18:28
I believe this is a known issue with the zstd library. We are tracking in #1706.

**Comment by mariamalikorg** [comment] 2023-05-15 18:32
Thank you for getting back to me. https://github.com/cockroachdb/pebble/issues/1706. is directed to v1.5.2 whereas DataDog/zstd updated to v1.5.5 a couple of weeks back. Do you think the solution will be provided and tested for v1.5.2 or v1.5.5? Second, Will you be able to provide the timeframe for when it will be addressed?

**Comment by nicktrav** [comment] 2023-05-15 23:11
#1706 is directed at upgrading that library in general (edited the title to make this clear). Looks like the issue is still there in `v1.5.5.`

> Do you think the solution will be provided and tested for v1.5.2 or v1.5.5? Second, Will you be able to provide the timeframe for when it will be addressed?

We don't have any plans right now to update this dependency. #1706 is also not planned at this time. We're happy to take contributions, if you'd like to dig into these failures.

**Comment by jbowens** [comment] 2023-08-11 19:19
Hi @mariamalikorg — This particular error was a result of the bug fixed in #2647.

**Closed by jbowens** 2023-08-11 19:19 UTC
Labels: T-storage, A-storage
