### ISSUE TITLE
panic: slice bounds out of range when using IndexedBatch

### ISSUE THREAD

**Issue by salarali** [cockroachdb/pebble#1480] opened 2022-01-27 16:40 UTC
Hi. I am using an IndexedBatch. When running it under very high load, it quickly panics with the error below.
I am mainly doing batch.Merge, batch.Delete operations and also using an batch.Iter

```
panic: runtime error: slice bounds out of range [6501306:6501297]

goroutine 660 [running]:
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).Add(0xc012252ed0, 0xc0006333b9, 0x6c, 0x2)
	/home/ec2-user/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220127153126-c8dad06cdd15/internal/batchskl/skl.go:190 +0x6bf
github.com/cockroachdb/pebble.(*Batch).Merge(0xc012252dc0, 0xc017e65f20, 0x52, 0x60, 0xc017e52c40, 0x6c, 0x70, 0x0, 0x0, 0x0)
	/home/ec2-user/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20220127153126-c8dad06cdd15/batch.go:544 +0xde
```

**Comment by nicktrav** [comment] 2022-02-11 22:27
Hi @salarali - apologies for the delay on this one.

Are you able to share a little more details on your workload? Do you have a minimal reproducer that we could work with?

We recently fixed a similar panic in the batch skiplist (see #1258), but this seems like it might be different.

**Comment by jbowens** [comment] 2022-08-29 21:22
Speculatively closing as a duplicate of #1258.

**Closed by jbowens** 2022-08-29 21:22 UTC
