### ISSUE TITLE
background error: pebble: keys must be added in order

### ISSUE THREAD

**Issue by nnsgmsone** [cockroachdb/pebble#577] opened 2020-03-18 03:49 UTC
What causes this phenomenon and how can I avoid it?

**Comment by petermattis** [comment] 2020-03-18 11:44
That error indicates either a bug in the application code or a bug in pebble. In either case, it is quite serious and not to be ignored. Can you provide details about what operations were being performed on the DB? What sha of Pebble you are using? Whether the DB had been migrated from RocksDB or not?

**Comment by nnsgmsone** [comment] 2020-03-18 12:49
@petermattis This is my project [.](https://github.com/deepfabric/thinkkv) I have provided a plugin to make pebble support s3. However, this problem occasionally occurs during runtime. Very confused what caused it.

**Comment by nnsgmsone** [comment] 2020-03-18 12:53
@petermattis  It may be a problem with my program, but I  ensure the consistency of vfs on s3. Could it be that the way I handle s3 is still not in place. I want to know what is causing this problem. Is the data messy?

**Comment by petermattis** [comment] 2020-03-18 13:19
The possibilities are a bit endless as to what could be causing the error. What the error is saying is that an attempt was made to construct an invalid SSTable. SSTable is short for Sorted String Table. The error you're encountering is due to keys being added out of order. That should never happen, but we have the check in place because it has in the past due to bugs. And RocksDB has seen similar problems due to bugs in RocksDB. As an example of the type of bug that can cause this error, RocksDB had a bug which caused cache collisions that resulted in data from the wrong sstable being read during compactions.

If you have a reproducible case, we can help you investigate further. If you don't have a reproducible case, you need to provide more info on what your program is doing. How is it using Pebble? What Pebble sha are you using? Are you using a custom `Comparer` or the default one?

**Comment by nnsgmsone** [comment] 2020-03-19 01:23
@petermattis  I use the default comparator, I just provided my own vfs, and I didn't modify the pebble code. I can send you test data. Is this useful to you?

**Comment by nnsgmsone** [comment] 2020-03-19 02:21
@petermattis May be a problem with my own project, I fixed a bug. I test again, it may be caused by my read problem

**Comment by petermattis** [comment] 2020-03-19 13:54
> @petermattis I use the default comparator, I just provided my own vfs, and I didn't modify the pebble code. I can send you test data. Is this useful to you?

Yes. Even more useful are step-by-step instructions on how to reproduce. This would include code or pointers to code. That's a general statement for filing any bug, not just against this repo.

> @petermattis May be a problem with my own project, I fixed a bug. I test again, it may be caused by my read problem

Ok. I'm going to close this issue for now. If you're still experiencing problems, feel free to open another bug, though please include more details about what you're doing.

**Closed by petermattis** 2020-03-19 13:54 UTC
