### ISSUE TITLE
commpaction: prioritize virtual sstables for compaction based on size ratios

### ISSUE THREAD

**Issue by itsbilal** [cockroachdb/pebble#2892] opened 2023-09-11 19:06 UTC
Currently, virtual sstables aren't specifically prioritized for compaction picking, even if the virtualized proportion of size relative to the underlying backing sstable is low (i.e. most of the physical sstable is unreferenced and can be cleared away if all virtual sstables on it got compacted). We can adjust this by boosting the overlappingBytes count in `pickCompactionSeedFile` by a factor like `f.Size/f.VirtualizedSize` (where f = FileMetadata).

**Comment by bananabrick** [comment] 2023-09-18 00:51
Duplicate of https://github.com/cockroachdb/pebble/issues/2323. Closing

**Closed by bananabrick** 2023-09-18 00:51 UTC
Labels: T-storage, A-storage
