### ISSUE TITLE
db: Open fails with 'open : no such file or directory'

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#3842] opened 2024-08-12 18:52 UTC
If you pass a relative path to Open as "foo", for example, using the pebble command:
```
./pebble bench ycsb --workload=A --num-ops 1 --initial-keys 1000000000 foo
```
it fails with:
```
error opening database at "foo": open : no such file or directory
```

This is because [mkdirAllAndSyncParents](https://github.com/cockroachdb/pebble/blob/9a4f0c8ce0a14117d4f30db8bc4086bbb3816897/checkpoint.go#L90) will attempt to open the empty directory.

I think we should actually be syncing the "." or "/", depending on whether the path was relative or absolute, and the MemFS should tolerate it. Currently the MemFS is particular about paths and does not tolerate paths relative to ".".

Jira issue: PEBBLE-238

**Comment by RaduBerinde** [comment] 2024-08-12 21:40
Is https://github.com/cockroachdb/pebble/issues/3509 related?

**Comment by itsbilal** [comment] 2024-08-13 19:40
Duplicate of #3509.

**Closed by itsbilal** 2024-08-13 19:40 UTC
Labels: C-bug, T-storage, A-storage, P-3
