### ISSUE TITLE
db.set is very slow with sync option

### ISSUE THREAD

**Issue by chensheng0** [cockroachdb/pebble#1028] opened 2020-12-20 14:20 UTC
Hi, very glad to see pebble. It is a great job.

I am new to pebble, and using example code in Readme. But I get the bad perfomance. 

```
db, err := pebble.Open("demo", &pebble.Options{})
	if err != nil {
		log.Fatal(err)
	}
	key := []byte("hello")
	t := time.Now()
	if err := db.Set(key, []byte("world"), pebble.Sync); err != nil {
		log.Fatal(err)
	}
	fmt.Println("single set time: ", time.Since(t))
}
```

and I got 
```
single set time:  11.102929ms
```

as you can see, set is very slow. I didn't paste a batch of set operations, but the result was the same.

Then I used rocksdb for test.

```
opts := rocksdb.NewDefaultOptions()
	opts.SetCreateIfMissingColumnFamilies(true)
	opts.SetCreateIfMissing(true)

	db, err := rocksdb.OpenDb(opts, "demo")
	if err != nil {
		panic(err)
	}
	opt := rocksdb.NewDefaultWriteOptions()
	opt.SetSync(true)
	t := time.Now()
	err = db.Put(opt, []byte("hello"), []byte("world"))
	if err != nil {
		panic(err)
	}
	fmt.Println("time: ", time.Since(t))
```

and I got:

```
time:  735.362µs
```

I think pebble should be very fast in write operation just like leveldb or rocksdb, can you guys give me some tips ?

**Comment by petermattis** [comment] 2020-12-20 18:28
Two likely possibilities:
* If you're testing this on Mac OS X, then Pebble's sync performance is different from RocksDB/LevelDB because Pebble is syncing to media using a Darwin specific call, while RocksDB/LevelDB use `fsync` which only syncs to the drive, not all the way down to the drive's media. 
* You don't have RocksDB/LevelDB configured to do synchronous writes. Those libraries default to not syncing writes to the WAL.

**Comment by chensheng0** [comment] 2020-12-21 01:29
I tested on Mac OS X. I'll try it on linux.

**Comment by yinhm** [comment] 2021-07-04 07:16
I have the same performance issue when using Sync.

I was porting a old project from rocksdb to pebble,  using `db.Set(key, value, pebble.NoSync)`
```

then found data lossing everytime I restart the server even thought I did call `db.Close()` db after signal received.

The next thing I do was changing pebble.NoSync to pebble.Sync,  then noticed testing became very slow, (ms to ten seconds).

The old tests are here, https://github.com/yinhm/friendfeed/blob/976671ef77d66beda5536d0eeedee6afe98b8eaf/storage/store_test.go#L239

```
func NewMetaStoreOptions() *pebble.Options {
	opts := &pebble.Options{
		LBaseMaxBytes:               64 << 20, // 64 MB
		Levels:                      make([]pebble.LevelOptions, 7),
		MemTableSize:                64 << 20, // 64 MB
		MemTableStopWritesThreshold: 4,
	}
	for i := 0; i < len(opts.Levels); i++ {
		l := &opts.Levels[i]
		l.BlockSize = 32 << 10       // 32 KB
		l.IndexBlockSize = 256 << 10 // 256 KB
		l.FilterPolicy = bloom.FilterPolicy(10)
		l.FilterType = pebble.TableFilter
		if i > 0 {
			l.TargetFileSize = opts.Levels[i-1].TargetFileSize * 2
		}
		l.EnsureDefaults()
	}
	opts.Levels[6].FilterPolicy = nil

	return opts
}
```

**Comment by petermattis** [comment] 2021-07-04 18:56
By default, RocksDB does not `fsync` data to disk, while Pebble does. The syncing of data to disk causes the performance difference. RocksDB does flush data to the OS buffer cache by default, but that only gives the impression of durability, not actual durability in the face of a machine crash. Pebble explicitly doesn't flush data to the OS buffer cache, preferring instead to make the lack of durability obvious.

**Comment by yinhm** [comment] 2021-07-05 02:58
I understand the design choice which tailored for cockroachdb, what suprised me was I had to manually Sync to disk even thought I have been closed the DB. Maybe, just maybe, a easy default setting for normal usercase would be nice.

Anyway, I changed to Sync for all writes and batch.Set for populating data in testing.

Thanks.

**Comment by petermattis** [comment] 2021-07-05 16:52
> I understand the design choice which tailored for cockroachdb, what suprised me was I had to manually Sync to disk even thought I have been closed the DB. Maybe, just maybe, a easy default setting for normal usercase would be nice.

`DB.Close()` should sync any data that has been written to the WAL. If you have a reproducible test case where data is lost after `DB.Close()` please file it as a separate issue.

**Comment by yinhm** [comment] 2021-07-06 05:03
After some dig around, I found the problem was rpc server closed first leads the whole app exit before db has the change to Close.

It was not a pebble problem.

Thanks.

**Comment by nicktrav** [comment] 2022-07-12 00:19
This issue appears to have been answered. Closing.

**Closed by nicktrav** 2022-07-12 00:19 UTC
