### ISSUE TITLE
Panic in log writer: `panic: sync: negative WaitGroup counter`

### ISSUE THREAD

**Issue by LINKIWI** [cockroachdb/pebble#2873] opened 2023-09-04 01:32 UTC
PebbleDB version: `v0.0.0-20230728201528-5e7f88523982`
Go version: `1.21.0`

Observation: A PebbleDB-based application sporadically panics during writes, with the following crash symptom:

```
panic: sync: negative WaitGroup counter
goroutine 10697 [running]:
sync.(*WaitGroup).Add(0x0?, 0xc00020e240?)
#011GOROOT/src/sync/waitgroup.go:62 +0xd8
sync.(*WaitGroup).Done(...)
#011GOROOT/src/sync/waitgroup.go:87
github.com/cockroachdb/pebble/record.(*syncQueue).pop(0xc00046a118, 0x121, 0x45e2?, {0x10a7700?, 0xc00051e0f0}, 0xc0002d64e0)
#011external/com_github_cockroachdb_pebble/record/log_writer.go:157 +0x109
github.com/cockroachdb/pebble/record.(*LogWriter).flushLoop(0xc00046a000, {0xe4d800, 0x17558e0})
#011external/com_github_cockroachdb_pebble/record/log_writer.go:465 +0x645
runtime/pprof.Do({0x10adca8?, 0x17558e0?}, {{0xc000298040?, 0xc0002f0190?, 0x10b1c38?}}, 0xc0001b9fc0)
#011GOROOT/src/runtime/pprof/runtime.go:51 +0x9d
github.com/cockroachdb/pebble/record.NewLogWriter.func2()
#011external/com_github_cockroachdb_pebble/record/log_writer.go:355 +0x56
created by github.com/cockroachdb/pebble/record.NewLogWriter in goroutine 10693
#011external/com_github_cockroachdb_pebble/record/log_writer.go:354 +0x416
```

The implicated callsite appears to be: https://github.com/cockroachdb/pebble/blob/a4fe05009372ba870cc6fe4e9b8c4873b576c549/record/log_writer.go#L157

Unfortunately, the crash is not deterministically reproducible, so I don't have a minimally reproducible example at this time.

Additional useful usage context:

* The application's only usage pattern is pretty simple: only involves creating new IndexedBatches, performing no more than ~10 R/W operations on the batch, followed by committing the batch with option `pebble.Sync`. Unfortunately this application is not open source.
* The above operations occur at a very low frequency: about 1 request every few minutes.
* With this throughput, the above crash occurs about once every few hours.

Apologies for the sparse bug report. I didn't find other issues or documentations covering this problem.

**Comment by RaduBerinde** [comment] 2023-09-04 19:12
Hi,

Thanks for the report!

`log_writer.go:465` looks like an error case. Obviously we must have a bug in that path, but the root cause of your issue is the flusher error itself. Can you add a log/printf with the error on this line (before `pop` is called)? That would get us more info. In the meantime, I'll see if I can figure out the bug in the error path.

**Comment by jbowens** [comment] 2023-09-22 14:12
Thanks. I'm going to close this out, but please re-open if necessary.

**Closed by jbowens** 2023-09-22 14:12 UTC
Labels: T-storage, A-storage

**Comment by RaduBerinde** [comment] 2023-09-22 14:20
@jbowens Is there something simple we can add to make this case have a less obscure panic? I asssume Close is not performance-sensitive so we could conceivably add some checks in there?

**Comment by jbowens** [comment] 2023-09-22 14:27
> Is there something simple we can add to make this case have a less obscure panic? I asssume Close is not performance-sensitive so we could conceivably add some checks in there?

Unfortunately it's tricky because we pool Batches. Seems like we could still add some facilities that at least could detect it in the case that the Batch is still sitting in the pool and hasn't yet been reused.

**Comment by RaduBerinde** [comment] 2023-09-22 15:28
Then we should at least improve the panic message or add a comment to look into whether you're calling Commit/Close multiple times.

**Comment by emilbon99** [comment] 2023-10-02 16:42
Looking for some clarification on this issue. Is it necessary to `Close` a batch after committing it? Or should you only call one of `Close` or `Commit` throughout the lifetime of the batch? I've been looking through the [Batch](https://pkg.go.dev/github.com/cockroachdb/pebble#Batch.Close) API reference and can't seem to find a clear answer to this.
