### ISSUE TITLE
Table filter is not used in read operation

### ISSUE THREAD

**Issue by rjl493456442** [cockroachdb/pebble#2759] opened 2023-07-20 06:13 UTC
Pebble can be configured to generate filter data in sstable in order to quickly
check if the requested item is included in this table or not. It's a huge optimization
when access a non-existing item in the database, and also can also improve the 
overall read performance by avoiding unnecessary OS reads.

However, i notice that the filter data is only be used in `seekPrefixGE`, but not
used in other read functions, e.g `seekGE`. It means for normal read operation
`db.Get(key)`, filter is never used.

This situation will be even worse when level0 has many files that have not been
compacted. Finding an item in level0 means all the sstables need to be checked
in order which is a huge overhead.

How can I re-enable the filter usage via configuration, or it needs some fixes?

**Comment by rjl493456442** [comment] 2023-07-24 03:17
Anyone wants to take a look? Perhaps @jbowens?

**Comment by merlimat** [comment] 2023-07-24 14:53
@jbowens Could this non-usage of bloom filter in `Get()` be the reason behind the issue described in #2766?

**Comment by jbowens** [comment] 2023-07-24 17:23
I'm going to close this out as a duplicate of #197.

**Closed by jbowens** 2023-07-24 17:23 UTC
Labels: T-storage, A-storage
