### ISSUE TITLE
 Got "keys must be added in order" erro cause the pebble db failed to start up.

### ISSUE THREAD

**Issue by changliang** [cockroachdb/pebble#1089] opened 2021-03-17 03:23 UTC
I saw the error is because of some record is out of order in sst file, what will cause it happen? 
And how to fix this when it happened,  it will cause the service can not start up..

**Comment by petermattis** [comment] 2021-03-21 16:37
@changliang This is a very serious error and indicates either a bug in Pebble, or in-memory or on-disk corruption, or a programmatic error. Keys must be inserted into sstables in order. Violating this invariant causes all sorts of badness to occur. If you're building sstables directly (using `sstable.Writer`), then this could be a programmatic error on your part. Assuming you're not doing that, the most likely cause is in-memory or on-disk corruption. The error should indicate which keys are involved and you may be able to determine that a bit seems to be flipped. If that is the case, you could possibly do surgery on the sstable (though you'd have to write your own tool to do this). If the keys do not appear to be corrupted, this could be a Pebble bug, though I put that at the bottom of the list because we haven't had any other reports of problems like this recently. If the situation is at all reproducible it would be useful to know more about what you did.

**Comment by changliang** [comment] 2021-03-26 02:54
@petermattis Thanks for your info, I will do more test and try to provide more information. 
Currently we use the the API of pebble to do set and get, no other raw write sstable logic.

**Comment by changliang** [comment] 2021-03-26 03:18
The error print is like this: 
`keys must be added in order: #0,DEL, #123,SET"`
 but to my understanding, it's not out of order? 
And there is a lot of SST files,  I don't know which SST file is corrupted.

**Comment by changliang** [comment] 2021-03-26 03:52
I found there is xxx.log file is corrupted. After I remove it, the pebble db can init successfully.
And after I started once, I move back the corrupted log file, the pebble db can still init successfully.

**Comment by changliang** [comment] 2021-03-26 03:57
I found there is xx.log file corrupted.
And After I remove it from the folder, the pebble db can start successful.
And After it started, I put the xx.log file back to the folder, it still can restart successful, and the xx.log file will be removed after it start.

**Comment by petermattis** [comment] 2021-05-10 12:54
This is very likely a duplicate of #1133.

**Closed by petermattis** 2021-05-10 12:54 UTC
