### ISSUE TITLE
tests: `TestWaitCancel` is flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1210] opened 2021-07-29 15:45 UTC
Observed the following fail -> pass flake:

```
--- FAIL: TestWaitCancel (0.49s)
    rate_test.go:379: lim.WaitN(will-cancel, lim, 3) = <nil> with delay 226.76901ms ; want <non-nil error> with delay 100ms
    rate_test.go:416: tokens:-1.99990963 last:2021-07-28 21:10:23.899098 +0000 UTC m=+0.202786071 lastEvent:2021-07-28 21:10:24.099088963 +0000 UTC m=+0.402777034
    rate_test.go:379: lim.WaitN(act-now-after-cancel, lim, 2) = <nil> with delay 267.191275ms ; want <nil> with delay 0s
```

**Comment by nicktrav** [comment] 2021-07-29 15:48
The test failed on the `go1.16-macos` job on a master build of 48179f1d4daec4fdf4fe4506f6b9c64b1b7e90cd.

**Comment by jbowens** [comment] 2021-07-29 19:06
I think this is a dupe of #1187. Maybe worth prioritizing given how flaky it seems.

**Closed** 2021-07-30 18:04 UTC
