### ISSUE TITLE
TestDiskHealthChecking_Filesystem_Close flaked

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/pebble#2716] opened 2023-07-10 14:55 UTC
Seen on https://github.com/cockroachdb/pebble/pull/2694: https://github.com/cockroachdb/pebble/actions/runs/5509409123/jobs/10042076587?pr=2694

```
2023-07-10T14:39:40.2935663Z === RUN   TestDiskHealthChecking_Filesystem_Close
2023-07-10T14:39:40.2935808Z     disk_health_test.go:545: 
2023-07-10T14:39:40.2936046Z         	Error Trace:	disk_health_test.go:545
2023-07-10T14:39:40.2936406Z         	Error:      	map[string]time.Duration{"foo":46332000} does not contain "bar"
2023-07-10T14:39:40.2936680Z         	Test:       	TestDiskHealthChecking_Filesystem_Close
2023-07-10T14:39:40.2936897Z --- FAIL: TestDiskHealthChecking_Filesystem_Close (0.13s)
```

**Comment by jbowens** [comment] 2023-07-10 21:12
Duplicate of #1718

**Closed as not planned by jbowens** 2023-07-10 21:12 UTC
Labels: T-storage, A-storage, skipped-test

**Comment by joshimhoff** [comment] 2023-07-10 21:17
Whoops. Thanks for duping!
