### ISSUE TITLE
internal/metamorphic: test failure on master

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/pebble#827] opened 2020-07-17 20:07 UTC
https://travis-ci.org/github/cockroachdb/pebble/jobs/709295022

**Comment by jbowens** [comment] 2020-07-17 20:14
Reproduced with
```
 go test -v -run TestMeta --seed 1595012965032913488 --keep
```
```
stress go test -v -run TestMeta --run-dir ./_meta/200717-200738.777/random-017 \
    --fail '\["rdlxviealrwhegnyflppxnbz"\] <nil> #1279' > failure.txt 2>&1
```

**Comment by jbowens** [comment] 2020-07-17 20:26
@itsbilal noticed that `random-017`'s options use flush splits but without sublevel compactions. I `stress`ed it under the same options without flush splits. It didn't trigger after 1,226 runs, so it seems probable that it's related to a flush splitting code path.

**Comment by itsbilal** [comment] 2020-07-20 17:09
Looking into this, an [L0,L3]->L3 compaction takes in these L3 files:

```
./000239.sst
rvnsjo#414,SET [627067667973616969]
rvnsjo-skjh#383,RANGEDEL
rvnsjo-skjh#356,RANGEDEL
skjh-tmgc#383,RANGEDEL
skjh-tmgc#356,RANGEDEL
tmgc-udkatvs#331,RANGEDEL
./000240.sst
tmgc#391,MERGE [786e627a]
tmgc-udkatvs#331,RANGEDEL
./000241.sst
tmgc#384,MERGE [666c7070]
tmgc-tvsalezade#383,RANGEDEL
tmgc-tvsalezade#331,RANGEDEL
./000242.sst
tmgc-tvsalezade#383,RANGEDEL
tmgc#375,SET [72646c78766965616c72776865676e79]
tmgc-tvsalezade#356,RANGEDEL
tvsalezade-udkatvs#331,RANGEDEL
./000243.sst
tvsalezade#410,DEL []
tvsalezade-udkatvs#383,RANGEDEL
tvsalezade-udkatvs#356,RANGEDEL
udkatvs-ueyaynwejsk#383,RANGEDEL
udkatvs-ueyaynwejsk#362,RANGEDEL
ueyaynwejsk-ugyd#424,RANGEDEL
ueyaynwejsk-ugyd#383,RANGEDEL
ueyaynwejsk-ugyd#331,RANGEDEL
```

And produces:

```
../000295.sst
rvnsjo#414,SET [627067667973616969]
../000296.sst
tmgc#391,MERGE [786e627a]
../000297.sst
tmgc#384,SET [72646c78766965616c72776865676e79666c7070]
tmgc-tvsalezade#383,RANGEDEL
../000298.sst
tvsalezade#410,DEL []
tvsalezade-udkatvs#383,RANGEDEL
udkatvs-ueyaynwejsk#383,RANGEDEL
ueyaynwejsk-ugyd#424,RANGEDEL
ueyaynwejsk-ugyd#383,RANGEDEL
ugyd-uqngjn#424,RANGEDEL
ugyd-uqngjn#383,RANGEDEL
uqngjn-vauhss#424,RANGEDEL
```

Look  just at the `tmgc` user key.

This is clearly wrong as the `#384,MERGE` ended up "Stepping over" the `#383,RANGEDEL` to merge with the `#375,SET`, basically resurfacing it.

I wonder if it's due to the fact that we had already emitted `tmgc-udkatvs#331,RANGEDEL` in `000239.sst` instead of fragmenting it at `tvsalezade`, messing up the next compaction's rangedel tombstone reading / fragmenting logic.

**Comment by itsbilal** [comment] 2020-07-20 21:09
When we initialize a `compactionIter`, it has two `levelIters` (one for point keys, one for range deletes) that are merged with a `mergingIter`. Here are the relevant input files for the problematic compaction:

```
./000240.sst   [tmgc#391,MERGE-tmgc#391,MERGE]
tmgc#391,MERGE [786e627a]
tmgc-udkatvs#331,RANGEDEL

./000241.sst   [tmgc#384,MERGE-tmgc#384,MERGE]
tmgc#384,MERGE [666c7070]
tmgc-tvsalezade#383,RANGEDEL
tmgc-tvsalezade#331,RANGEDEL

./000242.sst   [tmgc#383,RANGEDEL-tvsalezade#72057594037927935,RANGEDEL]
tmgc-tvsalezade#383,RANGEDEL
tmgc#375,SET [72646c78766965616c72776865676e79]
tmgc-tvsalezade#356,RANGEDEL
tvsalezade-udkatvs#331,RANGEDEL
```

The point key iter returns `tmgc#391,MERGE` and the rangedel one returns `tmgc-udkatvs#331,RANGEDEL`, both from 000240.sst. The merging iter continues `Next()`-ing the point iter while leaving the rangedel one in place. That point iter encounters `tmgc#384,MERGE`, which is in a different snapshot stripe so we just emit `tmgc#391,MERGE` as-is.

Then, after `tmgc#384,MERGE`, the point iter encounters `tmgc#375,SET` as it skips over all the rangedel tombstones (it's the point key iterator), and the compaction merges with it to make a `tmgc#384,SET`. Only after that do we `Next()` the rangedel level iterator, and encounter the range tombstone in the NEXT file (000241.sst) that should have covered the `tmgc#375,SET` key. So while 000241 has the range delete tombstone covering a key in itself, the compaction view of things lets the two iterators get out of sync just enough to resurface an old key.

I'm unsure what the best solution to this would be. Maybe the rangedel-only levelIter should not return range deletion tombstones outside a file's bounds; so by the time that levelIter moves down to the right file, it'd be able to return the correct tombstone that covers the SET.

**Comment by petermattis** [comment] 2020-07-21 16:36
How did we get these sstables that have range tombstones that lie completely outside the bounds of the sstable? We don't truncate range tombstones at creation time because we can only truncate to user keys, not to internal keys. But we do truncate range tombstones at read time. A range tombstone in an sstable only applies to the inclusive range of keys `[Smallest, Largest]`. This is enforced in normal read operations by `mergingIter`. So a range tombstone that lies completely outside of an sstable's bounds shouldn't have any effect, though it is clearly fouling up `compactionIter`. In addition to #832, I think we should prevent these range tombstones from being added to an sstable in the first place.

**Comment by itsbilal** [comment] 2020-07-21 18:03
@petermattis It makes sense when you look at the fact that these were the inputs into the L0 -> L3 compaction that produced those SSTs:

```
./000149.sst
skjh-udkatvs#331,RANGEDEL
./000150.sst
udkatvs-vlflbxa#331,RANGEDEL
./000189.sst
tmgc#391,MERGE [786e627a]
tmgc#384,MERGE [666c7070]
tmgc-tvsalezade#383,RANGEDEL
tmgc#375,SET [72646c78766965616c72776865676e79]
tmgc-tvsalezade#356,RANGEDEL
./000190.sst
tvsalezade#410,DEL []
tvsalezade-udkatvs#383,RANGEDEL
tvsalezade-udkatvs#356,RANGEDEL
udkatvs-ueyaynwejsk#383,RANGEDEL
udkatvs-ueyaynwejsk#362,RANGEDEL
```

The above are from two different flushes with splitting enabled.

Basically, `skjh-udkatvs#331,RANGEDEL` is an old, wide rangedel tombstone that's going to "sit around" in the fragmenter for a while. Since the `FlushTo` logic only takes in the end/limit user-key, which in this case would be `tmgc`, it will write out `tmgc-udkatvs#331,RANGEDEL`.

I thought about making the change to not write that tombstone to begin with, but it seems to be a pretty complex one in an already complicated writer-switching logic. We only calculate the file's bounds after all range tombstones are written, and changing that around to get a hold of the end sequence number could introduce some circular logic.

**Comment by petermattis** [comment] 2020-07-21 18:24
Ok. The part I wasn't understanding is how we were setting the upper bound for the sstable to a key that is not the range sentinel key. I think this deserves an explanatory comment in the code for how this can happen (perhaps reproducing the example here). While I knew a range tombstone could extend beyond an sstable's bounds, it was not at all obvious to me that it could lie entirely outside the bounds or that avoiding that situation is challenging given the current code structure. I'm imagining this commentary would be placed in `finishOutput()`.

**Comment by petermattis** [comment] 2020-07-21 18:47
I'm still worried that filtering range tombstones that lie outside of an sstable's bounds is not sufficient. `levelIter` wants the keys it returns to be in sorted order, but the range tombstones above are violating that. In normal iters, we truncate the range tombstones to the sstable boundaries, but not so when a `levelIter` is used as part of a `compactionIter`.

One possible fix is to add each sstable's range del iters as another level to the `mergingIter`. We already do this when using inputs from L0. I'm proposing we do the same for inputs from all levels. Would that also fix this problem?

**Comment by itsbilal** [comment] 2020-07-21 19:00
I'm less worried, maybe because I've yet to think of a scenario where this change would not be a sufficient fix to this type of a problem. We generally tend to take good care of ensuring an sstable has a "correct" view of range tombstones within its bounds, and the relative rarity of bugs like this (it takes ~50+ tries with `stress` to reproduce, under one specific set of options) seems to suggest that as well.

And yes, having per-sstable iterators inside the compactionIter's mergingIter would solve this problem too. Though I wonder if that'll be too many open readers at once, which could be inefficient in other ways (such as in the form of a large mergingIter heap).

**Comment by petermattis** [comment] 2020-07-21 19:10
> I'm less worried, maybe because I've yet to think of a scenario where this change would not be a sufficient fix to this type of a problem.

That is reassuring, though my paranoia in this area is born of hard earned experience.

> And yes, having per-sstable iterators inside the compactionIter's mergingIter would solve this problem too. Though I wonder if that'll be too many open readers at once, which could be inefficient in other ways (such as in the form of a large mergingIter heap).

We'd only add `mergingIter` levels for sstables that contain range tombstones. The rangedel iters don't keep the sstable reader open (because we copy the range tombstones). I think doing both fixes is worthwhile.

**Closed** 2020-07-22 20:09 UTC
Labels: bug
